# Generated by Django 5.0.6 on 2025-05-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.URLField()),
                ('company_name', models.CharField(max_length=100)),
                ('price_band', models.CharField(max_length=50)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('issue_size', models.CharField(max_length=100)),
                ('issue_type', models.CharField(max_length=50)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('ipo_price', models.FloatField()),
                ('listing_price', models.FloatField()),
                ('listing_gain', models.FloatField()),
                ('cmp', models.FloatField()),
                ('current_return', models.FloatField()),
                ('rhp_pdf', models.URLField()),
                ('drhp_pdf', models.URLField()),
            ],
        ),
    ]
